### ISSUE TITLE
XML Import

### ISSUE THREAD

**Issue by taunusweb** [dwenzel/t3import_export#10]
Hi there,
I tested the xml-import, I think it's working so far, but i don't know, how to get the data into a table? Do you have a working TS-Example for that issue? Thanks in advance.
Uli

**Comment by dwenzel** [comment]
Hi Uli,
thank you for your feedback. 
I assume you already read the [Documentation](https://github.com/dwenzel/t3import_export/tree/master#table-of-contents). 
There you can find an [overview](https://github.com/dwenzel/t3import_export/blob/master/Documentation/OVERVIEW.md) and a general description of the [configuration](https://github.com/dwenzel/t3import_export/blob/master/Documentation/CONFIGURATION.md).

But there is still a lot of documentation missing. I will try and describe the most important aspects of persisting any records here.

### From Source to Target
In order to get your data into a table a _data target_ must be configured. 
The following data targets are implemented already:
* DataTargetDB
* DataTargetRepository
* DataTargetXML

### Target Repository
The default target is `CPSIT\T3importExport\Persistence\DataTargetRepository`. 
Its minimal configuration consists of the class name of the object.

```
module.tx_t3importexport.settings.import.tasks.exampleTask {
  target.object.class = DWenzel\T3events\Domain\Model\Event
}
```
It expects an array of (Extbase) domain objects and persists them via their repository. 

### Get Objects
There is a converter which can create domain objects from arrays: `CPSIT\T3importExport\Component\Converter\ArrayToDomainObject`
See [its documentation](https://github.com/dwenzel/t3import_export/blob/master/Documentation/Components/Converters/ArrayToDomainObject.md) for details.
This converter leverages the (Extbase) PropertyMapper and therefore "knows" the correct mapping of properties even if they are child objects.

I would *not* recommend using it, if your target is not a complex object. 
It is not possible to use it, if no domain object exist or if no repository exists.
 
### What else
Have a look at the [DataTargetDB](https://github.com/dwenzel/t3import_export/blob/develop/Documentation/Persistence/DataTargetDB.md). (Note: the link points to the _development_ branch. The current _master_ version contains an error.)

It is much simpler to configure and there is even a [working example](https://github.com/dwenzel/t3import_export/blob/develop/Resources/Public/Examples/TypoScript/csv2ttContent.ts). (Note: This example *actually creates* `tt_content` records. It should not be used in production environments.)

### Roll Your Own (Target)
You may use a custom class. It *must* implement the `CPSIT\T3importExport\Persistence\DataTargetInterface`:
```
module.tx_t3importexport.settings.import.tasks.exampleTask {
  target {
    class = VendorName\PackageName\Persistence\MyCoolDataTarget
    config {
      ...
    }
  }
}
```

cheers
Dirk
