### ISSUE TITLE
no config with matching key 'export' found

### ISSUE THREAD

**Issue by metaxos** [dwenzel/t3import_export#8]
Hi there

I just installed your extension on a 8.7.3 installation. Clicking on Export I get following error message. I have included your Ext in static.

> #123476532: no config with matching key 'export' found, only: ('import') 

![screen shot 2017-07-18 at 10 07 27](https://user-images.githubusercontent.com/5360113/28306848-3a9973d6-6ba1-11e7-91fa-6c359f3fb90d.png)

Any hint for me?

**Comment by dwenzel** [comment]
Hi @metaxos,
this message just means what is says. There isn't any configuration for exports.
It might be confusing that an exeption is thrown. 
The behaviour will be changed in future version (to displaying just a notice instead of an exception).

If you want to export anything using t3import_export, you will have to configure export tasks or sets via TypoScript. 

There is no default configuration and no function in the backend modules if none is provided. 
Please see `Resources/Public/Examples/TypoScript` for a - quite simple - example configuration (import).
